## Numpy Array

In [1]:
import numpy as np

In [2]:
array_1d = np.array([1,2,3,4,5])
print(array_1d)

[1 2 3 4 5]


In [4]:
array_2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [7]:
list = ['kojo','kwame','kwesi','kwabena']
arr = np.array(list)
print(arr)

['kojo' 'kwame' 'kwesi' 'kwabena']


In [12]:
# identity_array = np.identity(4)
# print(identity_array)

#alternate
eye_array = np.eye(4) * 8
print(eye_array)

[[8. 0. 0. 0.]
 [0. 8. 0. 0.]
 [0. 0. 8. 0.]
 [0. 0. 0. 8.]]


In [14]:
zeros_array = np.zeros((2,3))
print(zeros_array)
type_of_array = type(zeros_array)
print(type_of_array)

[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [15]:
arr = np.linspace(0, 100, 5)
print(arr)

[  0.  25.  50.  75. 100.]


In [19]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array[2] 

array([7, 8, 9])

In [ ]:
arr1 = np.arrange(0,5)
arr2 = np.arrange(5,11)

arr1 + arr2