## Numpy Array

In [76]:
import numpy as np

In [77]:
# list = ['kojo','kwame','kwesi','kwabena']
# arr = np.array(list)
# print(arr)

In [78]:
# identity_array = np.identity(4)
# print(identity_array)

#alternate
eye_array = np.eye(4) * 8
print(eye_array)

[[8. 0. 0. 0.]
 [0. 8. 0. 0.]
 [0. 0. 8. 0.]
 [0. 0. 0. 8.]]


In [79]:
zeros_array = np.zeros((2,3))
print(zeros_array)
type_of_array = type(zeros_array)
print(type_of_array)

[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [80]:
arr = np.linspace(0, 100, 5)
print(arr)

[  0.  25.  50.  75. 100.]


In [81]:
# array0 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# array0[2]

In [82]:
arr33= np.arange(0,6)
arr2 = np.arange(5,11)

arr33 + arr2

array([ 5,  7,  9, 11, 13, 15])

In [83]:
## multiplication
arr33*arr2

array([ 0,  6, 14, 24, 36, 50])

In [84]:
array_shape = np.array = ([[1,2,3],[4,5,6],[7,8,9]])
array_shape
np.shape(array_shape)

(3, 3)

In [85]:
array_reshape = np.reshape(array_shape, newshape=(9,1))
array_reshape

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [86]:
# we can also use resize

# array_reshape=np.resize(array_reshape, (3,3))
array_reshape

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [87]:
#joining arrays we use concatenate
np.concatenate((array_reshape, array_reshape), axis=None) #we set axis to none to flatten the array which will be very useful in deep learning

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
# array_1d = np.array([1,2,3,4,5])
# print(array_1d)